### ISSUE TITLE
Some undefined variables in the new code

### ISSUE THREAD

**Issue by KalraA** [tranluan/Nonlinear_Face_3DMM#21]
Hi,

@tranluan the new commits posted last week. I tried running the code and I'm getting some variables that aren't defined. Do you know what edits we need to make to fix it?

**Input:** python main_non_linear_3DMM.py 
**Output**
{'batch_size': 64,
 'beta1': 0.5,
 'c_dim': 3,
 'checkpoint_dir': 'checkpoint',
 'dataset': 'celebA',
 'df_dim': 32,
 'dfc_dim': 512,
 'epoch': 1000,
 'gf_dim': 32,
 'gfc_dim': 512,
 'gpu': '0',
 'h': False,
 'help': False,
 'helpfull': False,
 'helpshort': False,
 'image_size': 108,
 'is_batchwise_white_shading': False,
 'is_const_albedo': False,
 'is_const_local_albedo': False,
 'is_crop': False,
 'is_gt_m': False,
 'is_partbase_albedo': False,
 'is_pretrain': False,
 'is_reduce': False,
 'is_smoothness': False,
 'is_train': True,
 'is_using_frecon': False,
 'is_using_graddiff': False,
 'is_using_landmark': False,
 'is_using_linear': False,
 'is_using_recon': False,
 'is_using_symetry': False,
 'is_with_y': True,
 'learning_rate': 0.0002,
 'output_size': 224,
 'sample_size': 64,
 'samples_dir': 'samples',
 'train_size': 5000000,
 'visualize': False,
 'z_dim': 50}
2019-07-22 11:46:36.925753: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-07-22 11:46:37.039450: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:998] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-07-22 11:46:37.040339: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x5a2dbb0 executing computations on platform CUDA. Devices:
2019-07-22 11:46:37.040355: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): GeForce RTX 2060, Compute Capability 7.5
2019-07-22 11:46:37.062342: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2208000000 Hz
2019-07-22 11:46:37.062777: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x5a97540 executing computations on platform Host. Devices:
2019-07-22 11:46:37.062796: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
2019-07-22 11:46:37.062964: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties: 
name: GeForce RTX 2060 major: 7 minor: 5 memoryClockRate(GHz): 1.2
pciBusID: 0000:01:00.0
totalMemory: 5.77GiB freeMemory: 4.55GiB
2019-07-22 11:46:37.062980: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
2019-07-22 11:46:37.065177: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-07-22 11:46:37.065190: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0 
2019-07-22 11:46:37.065199: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N 
2019-07-22 11:46:37.065300: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 4723 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2060, pci bus id: 0000:01:00.0, compute capability: 7.5)
Loading 3DMM tri ...
    DONE
Loading 3DMM vertex tri ...
    DONE
Loading ./3DMM_definition/3DMM_shape_basis.dat ...
    DONE
Loading ./3DMM_definition/3DMM_exp_basis.dat ...
    DONE
Making make_parallel for 1 gpu(s)
WARNING:tensorflow:From /home/rayquaza/.local/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py:3632: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
[64, 102]
[64, 102]
[64, 256]
WARNING:tensorflow:From /home/rayquaza/Documents/faces/Nonlinear_Face_3DMM/ops.py:128: conv2d_transpose (from tensorflow.python.layers.convolutional) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.conv2d_transpose instead.
[64, 256]
Loading 3DMM tri ...
    DONE
Loading 3DMM vertex tri ...
    DONE
WARNING:tensorflow:From /home/rayquaza/Documents/faces/Nonlinear_Face_3DMM/rendering_ops.py:544: calling l2_normalize (from tensorflow.python.ops.nn_impl) with dim is deprecated and will be removed in a future version.
Instructions for updating:
dim is deprecated, use axis instead
sh.get_shape()
(64, 43008, 1, 9)
L1.get_shape()
(64, 43008, 9, 1)
Loading 3DMM tri ...
    DONE
Loading 3DMM vertex tri ...
    DONE
Loading 3DMM keypoints ...
Loading 3DMM keypoints ...
WARNING:tensorflow:From /home/rayquaza/Documents/faces/Nonlinear_Face_3DMM/ops.py:222: div (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Deprecated in favor of operator or tf.math.divide.
Loading AFW ...
    DONE. Finish loading AFW with 5207 images
Loading AFW_Flip ...
    DONE. Finish loading AFW_Flip with 5207 images
Loading HELEN ...
    DONE. Finish loading HELEN with 37676 images
Loading HELEN_Flip ...
    DONE. Finish loading HELEN_Flip with 37676 images
Loading IBUG ...
    DONE. Finish loading IBUG with 1786 images
Loading IBUG_Flip ...
    DONE. Finish loading IBUG_Flip with 1786 images
Loading LFPW ...
    DONE. Finish loading LFPW with 16556 images
Loading LFPW_Flip ...
    DONE. Finish loading LFPW_Flip with 16556 images
Traceback (most recent call last):
  File "main_non_linear_3DMM.py", line 87, in <module>
    tf.app.run()
  File "/home/rayquaza/.local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "main_non_linear_3DMM.py", line 70, in main
    dcgan.train(FLAGS)
  File "/home/rayquaza/Documents/faces/Nonlinear_Face_3DMM/model_non_linear_3DMM.py", line 405, in train
    print("Valid images %d/%d" % ( len(valid_300W_idx), self.images_300W.shape[0] ))
NameError: global name 'valid_300W_idx' is not defined

**Comment by tranluan** [comment]
Sorry. It's just a typo, please replace 'valid_300W_idx' by 'valid_idx'.

**Comment by KalraA** [comment]
Thanks for the quick response! This is what I get now:
    print("Valid images %d/%d" % ( len(valid_idx), self.images_300W.shape[0] ))
AttributeError: 'DCGAN' object has no attribute 'images_300W

Also if you would like, once I get this working, I can submit a pull request with all the bugs fixed and documentation added for everyone else.

**Comment by tranluan** [comment]
self.images_300W is self.image_filenames

Please submit a pull request. I appreciate it.

**Comment by KalraA** [comment]
Ya, I figured that one out, now I'm stuck on 
ffeed_dict[self.texture_labels_fn_300W[i]] = _300W_LP_DIR + 'texture/'+ image2texture_fn(batch_300W_images_fn[i])
NameError: global name 'image2texture_fn' is not defined

**Comment by tranluan** [comment]
The function image2texture_fn try to convert image filename into texture filename. Since multiple images reuse the same ground truth texture.
Sorry. That's way too many errors that shouldn't be there.

Please add this to utils.py

def image2texture_fn(image_fn):
    last = image_fn[-7:].find('_')
    if (last < 0):
        return image_fn
    else:
        return image_fn[:-7 + last] + '_0.png'

**Comment by KalraA** [comment]
Ok great, now it's training. So I guess the next question is how can I make sure that it reproduces the results in the paper? Is there a testing script? or a online pretrained model we can compare against?

**Comment by tranluan** [comment]
The weights here are set the same as my most recent experiment.
I usually run pretrain stage for 1 days (~15 epochs) on 4 TitanX GPU with all losses. Then the weight for S and m are set to 0 or reduced significantly.
I don't have access to GPUs at the moment to validate all the hyper parameters on this "clean up" implementation. That's why I was hesitating posting the code. Gonna post the command to run the code soon.

**Comment by KalraA** [comment]
Can you share with me the command to run the pretrained model?

**Comment by tranluan** [comment]
```
python main_non_linear_3DMM_lighting_all2d_hybrid.py --batch_size 128 --sample_size 128 --is_train True --learning_rate 0.001 --ouput_size  224 \
   --gf_dim 32 --df_dim 32 --dfc_dim 320 --gfc_dim 320 --z_dim 20 --c_dim 3 \
   --is_using_landmark True  --shape_loss l2 --tex_loss l1 \
   --is_using_recon False --is_using_frecon False --is_partbase_albedo False --is_using_symetry True  \
   --is_albedo_supervision False --is_batchwise_white_shading True --is_const_albedo True --is_const_local_albedo True --is_smoothness True 
  --gpu 0,1,2,3 \

```

**Comment by KalraA** [comment]
This is the code to train, what about to just test out the model on some images and visualize those results?

**Comment by tranluan** [comment]
You can just simply change the network setting is_train = False, then feed the image to the network. You can use any library to visualize the 3D shape (topology is given in tri file).

Maybe I'll add later if I have time.

**Comment by huxianer** [comment]
@tranluan Can you share with me the command to test the model,Thank you

**Comment by KalraA** [comment]
@tranluan What is the path to the weights? The checkpoint path is not found as it looks to me.

**Comment by KalraA** [comment]
line 73, in main
    dcgan.test(FLAGS, True)
AttributeError: 'DCGAN' object has no attribute 'test'
^ What do I do here?

**Comment by dochenms** [comment]
@KalraA  what is your tensorflow  and cuda version? I have tried to run this code, but encounter an error of " [[ZbufferTriV2Sz224]]
Errors may have originated from an input operation.
Input Source operations connected to node ZbufferTriV2Sz224:"

**Comment by xingmimfl** [comment]
> ```
> python main_non_linear_3DMM.py --batch_size 128 --sample_size 128 --is_train True --learning_rate 0.001 --ouput_size  224 \
>    --gf_dim 32 --df_dim 32 --dfc_dim 320 --gfc_dim 320 --z_dim 20 --c_dim 3 \
>    --is_using_landmark True  --shape_loss l2 --tex_loss l1 \
>    --is_using_recon False --is_using_frecon False --is_partbase_albedo False --is_using_symetry True  \
>    --is_albedo_supervision False --is_batchwise_white_shading True --is_const_albedo True --is_const_local_albedo True --is_smoothness True 
>   --gpu 0,1,2,3 \
> ```
> 
> Turn off the "--is_using_recon", "--is_using_frecon" could speed up the training, (as the rendering layer is slow T_T). #1

loss is NAN using above command

**Comment by huyanfei-cqupt** [comment]
> Hi,
> 
> @tranluan the new commits posted last week. I tried running the code and I'm getting some variables that aren't defined. Do you know what edits we need to make to fix it?
> 
> **Input:** python main_non_linear_3DMM.py
> **Output**
> {'batch_size': 64,
> 'beta1': 0.5,
> 'c_dim': 3,
> 'checkpoint_dir': 'checkpoint',
> 'dataset': 'celebA',
> 'df_dim': 32,
> 'dfc_dim': 512,
> 'epoch': 1000,
> 'gf_dim': 32,
> 'gfc_dim': 512,
> 'gpu': '0',
> 'h': False,
> 'help': False,
> 'helpfull': False,
> 'helpshort': False,
> 'image_size': 108,
> 'is_batchwise_white_shading': False,
> 'is_const_albedo': False,
> 'is_const_local_albedo': False,
> 'is_crop': False,
> 'is_gt_m': False,
> 'is_partbase_albedo': False,
> 'is_pretrain': False,
> 'is_reduce': False,
> 'is_smoothness': False,
> 'is_train': True,
> 'is_using_frecon': False,
> 'is_using_graddiff': False,
> 'is_using_landmark': False,
> 'is_using_linear': False,
> 'is_using_recon': False,
> 'is_using_symetry': False,
> 'is_with_y': True,
> 'learning_rate': 0.0002,
> 'output_size': 224,
> 'sample_size': 64,
> 'samples_dir': 'samples',
> 'train_size': 5000000,
> 'visualize': False,
> 'z_dim': 50}
> 2019-07-22 11:46:36.925753: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
> 2019-07-22 11:46:37.039450: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:998] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
> 2019-07-22 11:46:37.040339: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x5a2dbb0 executing computations on platform CUDA. Devices:
> 2019-07-22 11:46:37.040355: I tensorflow/compiler/xla/service/service.cc:158] StreamExecutor device (0): GeForce RTX 2060, Compute Capability 7.5
> 2019-07-22 11:46:37.062342: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2208000000 Hz
> 2019-07-22 11:46:37.062777: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x5a97540 executing computations on platform Host. Devices:
> 2019-07-22 11:46:37.062796: I tensorflow/compiler/xla/service/service.cc:158] StreamExecutor device (0): ,
> 2019-07-22 11:46:37.062964: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties:
> name: GeForce RTX 2060 major: 7 minor: 5 memoryClockRate(GHz): 1.2
> pciBusID: 0000:01:00.0
> totalMemory: 5.77GiB freeMemory: 4.55GiB
> 2019-07-22 11:46:37.062980: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
> 2019-07-22 11:46:37.065177: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
> 2019-07-22 11:46:37.065190: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990] 0
> 2019-07-22 11:46:37.065199: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0: N
> 2019-07-22 11:46:37.065300: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 4723 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2060, pci bus id: 0000:01:00.0, compute capability: 7.5)
> Loading 3DMM tri ...
> DONE
> Loading 3DMM vertex tri ...
> DONE
> Loading ./3DMM_definition/3DMM_shape_basis.dat ...
> DONE
> Loading ./3DMM_definition/3DMM_exp_basis.dat ...
> DONE
> Making make_parallel for 1 gpu(s)
> WARNING:tensorflow:From /home/rayquaza/.local/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py:3632: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
> Instructions for updating:
> Colocations handled automatically by placer.
> [64, 102]
> [64, 102]
> [64, 256]
> WARNING:tensorflow:From /home/rayquaza/Documents/faces/Nonlinear_Face_3DMM/ops.py:128: conv2d_transpose (from tensorflow.python.layers.convolutional) is deprecated and will be removed in a future version.
> Instructions for updating:
> Use keras.layers.conv2d_transpose instead.
> [64, 256]
> Loading 3DMM tri ...
> DONE
> Loading 3DMM vertex tri ...
> DONE
> WARNING:tensorflow:From /home/rayquaza/Documents/faces/Nonlinear_Face_3DMM/rendering_ops.py:544: calling l2_normalize (from tensorflow.python.ops.nn_impl) with dim is deprecated and will be removed in a future version.
> Instructions for updating:
> dim is deprecated, use axis instead
> sh.get_shape()
> (64, 43008, 1, 9)
> L1.get_shape()
> (64, 43008, 9, 1)
> Loading 3DMM tri ...
> DONE
> Loading 3DMM vertex tri ...
> DONE
> Loading 3DMM keypoints ...
> Loading 3DMM keypoints ...
> WARNING:tensorflow:From /home/rayquaza/Documents/faces/Nonlinear_Face_3DMM/ops.py:222: div (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
> Instructions for updating:
> Deprecated in favor of operator or tf.math.divide.
> Loading AFW ...
> DONE. Finish loading AFW with 5207 images
> Loading AFW_Flip ...
> DONE. Finish loading AFW_Flip with 5207 images
> Loading HELEN ...
> DONE. Finish loading HELEN with 37676 images
> Loading HELEN_Flip ...
> DONE. Finish loading HELEN_Flip with 37676 images
> Loading IBUG ...
> DONE. Finish loading IBUG with 1786 images
> Loading IBUG_Flip ...
> DONE. Finish loading IBUG_Flip with 1786 images
> Loading LFPW ...
> DONE. Finish loading LFPW with 16556 images
> Loading LFPW_Flip ...
> DONE. Finish loading LFPW_Flip with 16556 images
> Traceback (most recent call last):
> File "main_non_linear_3DMM.py", line 87, in
> tf.app.run()
> File "/home/rayquaza/.local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
> _sys.exit(main(argv))
> File "main_non_linear_3DMM.py", line 70, in main
> dcgan.train(FLAGS)
> File "/home/rayquaza/Documents/faces/Nonlinear_Face_3DMM/model_non_linear_3DMM.py", line 405, in train
> print("Valid images %d/%d" % ( len(valid_300W_idx), self.images_300W.shape[0] ))
> NameError: global name 'valid_300W_idx' is not defined
hi, I try to use the author provide   command to run the main_nonlinear_3DMM.py ,but meet the follow error,  can you help me to complain this problem?  thank you very much.
NotFoundError: ./TF_newop/cuda_op_kernel_v2_sz224.so: cannot open shared object file: No such file or directory #41
the command as follow:
python main_non_linear_3DMM.py --batch_size 128 --sample_size 128 --is_train True --learning_rate 0.001 --ouput_size  224 \
   --gf_dim 32 --df_dim 32 --dfc_dim 320 --gfc_dim 320 --z_dim 20 --c_dim 3 \
   --is_using_landmark True  --shape_loss l2 --tex_loss l1 \
   --is_using_recon False --is_using_frecon False --is_partbase_albedo False --is_using_symetry True  \
   --is_albedo_supervision False --is_batchwise_white_shading True --is_const_albedo True --is_const_local_albedo True --is_smoothness True 
  --gpu 0

**Comment by HOMGH** [comment]
> Ok great, now it's training. So I guess the next question is how can I make sure that it reproduces the results in the paper? Is there a testing script? or a online pretrained model we can compare against?

Hi @KalraA 
I just saw your comments here. It seems that you could train their model. As I have some issues with the rendering module, would you please give me the details of your environment you used for training this code? I'm using ubuntu 18, python 2.7 and tensorflow 1.8 and I'm facing errors when I run the main code. The error I get when I run the rendering_example.py is  as follows:
The error I get when I run rendering_example.py:
InternalError: Blas xGEMMBatched launch failed : a.shape=[16,4,3], b.shape=[16,53215,4], m=3, n=53215, k=4, batch_size=16
[[Node: MatMul = BatchMatMul[T=DT_FLOAT, adj_x=true, adj_y=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](concat, concat_1)]]
[[Node: Reshape_43/_147 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1301_Reshape_43", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Any advice is highly appreciated.

**Comment by cyjouc** [comment]
> Hi,
> 
> @tranluan the new commits posted last week. I tried running the code and I'm getting some variables that aren't defined. Do you know what edits we need to make to fix it?
> 
> **Input:** python main_non_linear_3DMM.py
> **Output**
> {'batch_size': 64,
> 'beta1': 0.5,
> 'c_dim': 3,
> 'checkpoint_dir': 'checkpoint',
> 'dataset': 'celebA',
> 'df_dim': 32,
> 'dfc_dim': 512,
> 'epoch': 1000,
> 'gf_dim': 32,
> 'gfc_dim': 512,
> 'gpu': '0',
> 'h': False,
> 'help': False,
> 'helpfull': False,
> 'helpshort': False,
> 'image_size': 108,
> 'is_batchwise_white_shading': False,
> 'is_const_albedo': False,
> 'is_const_local_albedo': False,
> 'is_crop': False,
> 'is_gt_m': False,
> 'is_partbase_albedo': False,
> 'is_pretrain': False,
> 'is_reduce': False,
> 'is_smoothness': False,
> 'is_train': True,
> 'is_using_frecon': False,
> 'is_using_graddiff': False,
> 'is_using_landmark': False,
> 'is_using_linear': False,
> 'is_using_recon': False,
> 'is_using_symetry': False,
> 'is_with_y': True,
> 'learning_rate': 0.0002,
> 'output_size': 224,
> 'sample_size': 64,
> 'samples_dir': 'samples',
> 'train_size': 5000000,
> 'visualize': False,
> 'z_dim': 50}
> 2019-07-22 11:46:36.925753: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
> 2019-07-22 11:46:37.039450: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:998] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
> 2019-07-22 11:46:37.040339: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x5a2dbb0 executing computations on platform CUDA. Devices:
> 2019-07-22 11:46:37.040355: I tensorflow/compiler/xla/service/service.cc:158] StreamExecutor device (0): GeForce RTX 2060, Compute Capability 7.5
> 2019-07-22 11:46:37.062342: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2208000000 Hz
> 2019-07-22 11:46:37.062777: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x5a97540 executing computations on platform Host. Devices:
> 2019-07-22 11:46:37.062796: I tensorflow/compiler/xla/service/service.cc:158] StreamExecutor device (0): ,
> 2019-07-22 11:46:37.062964: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties:
> name: GeForce RTX 2060 major: 7 minor: 5 memoryClockRate(GHz): 1.2
> pciBusID: 0000:01:00.0
> totalMemory: 5.77GiB freeMemory: 4.55GiB
> 2019-07-22 11:46:37.062980: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
> 2019-07-22 11:46:37.065177: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
> 2019-07-22 11:46:37.065190: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990] 0
> 2019-07-22 11:46:37.065199: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0: N
> 2019-07-22 11:46:37.065300: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 4723 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2060, pci bus id: 0000:01:00.0, compute capability: 7.5)
> Loading 3DMM tri ...
> DONE
> Loading 3DMM vertex tri ...
> DONE
> Loading ./3DMM_definition/3DMM_shape_basis.dat ...
> DONE
> Loading ./3DMM_definition/3DMM_exp_basis.dat ...
> DONE
> Making make_parallel for 1 gpu(s)
> WARNING:tensorflow:From /home/rayquaza/.local/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py:3632: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
> Instructions for updating:
> Colocations handled automatically by placer.
> [64, 102]
> [64, 102]
> [64, 256]
> WARNING:tensorflow:From /home/rayquaza/Documents/faces/Nonlinear_Face_3DMM/ops.py:128: conv2d_transpose (from tensorflow.python.layers.convolutional) is deprecated and will be removed in a future version.
> Instructions for updating:
> Use keras.layers.conv2d_transpose instead.
> [64, 256]
> Loading 3DMM tri ...
> DONE
> Loading 3DMM vertex tri ...
> DONE
> WARNING:tensorflow:From /home/rayquaza/Documents/faces/Nonlinear_Face_3DMM/rendering_ops.py:544: calling l2_normalize (from tensorflow.python.ops.nn_impl) with dim is deprecated and will be removed in a future version.
> Instructions for updating:
> dim is deprecated, use axis instead
> sh.get_shape()
> (64, 43008, 1, 9)
> L1.get_shape()
> (64, 43008, 9, 1)
> Loading 3DMM tri ...
> DONE
> Loading 3DMM vertex tri ...
> DONE
> Loading 3DMM keypoints ...
> Loading 3DMM keypoints ...
> WARNING:tensorflow:From /home/rayquaza/Documents/faces/Nonlinear_Face_3DMM/ops.py:222: div (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
> Instructions for updating:
> Deprecated in favor of operator or tf.math.divide.
> Loading AFW ...
> DONE. Finish loading AFW with 5207 images
> Loading AFW_Flip ...
> DONE. Finish loading AFW_Flip with 5207 images
> Loading HELEN ...
> DONE. Finish loading HELEN with 37676 images
> Loading HELEN_Flip ...
> DONE. Finish loading HELEN_Flip with 37676 images
> Loading IBUG ...
> DONE. Finish loading IBUG with 1786 images
> Loading IBUG_Flip ...
> DONE. Finish loading IBUG_Flip with 1786 images
> Loading LFPW ...
> DONE. Finish loading LFPW with 16556 images
> Loading LFPW_Flip ...
> DONE. Finish loading LFPW_Flip with 16556 images
> Traceback (most recent call last):
> File "main_non_linear_3DMM.py", line 87, in
> tf.app.run()
> File "/home/rayquaza/.local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
> _sys.exit(main(argv))
> File "main_non_linear_3DMM.py", line 70, in main
> dcgan.train(FLAGS)
> File "/home/rayquaza/Documents/faces/Nonlinear_Face_3DMM/model_non_linear_3DMM.py", line 405, in train
> print("Valid images %d/%d" % ( len(valid_300W_idx), self.images_300W.shape[0] ))
> NameError: global name 'valid_300W_idx' is not defined

Hi,I occur to the error:

NameError: global name '_300W_LP_DIR' is not defined

**Comment by cyjouc** [comment]
> > Ok great, now it's training. So I guess the next question is how can I make sure that it reproduces the results in the paper? Is there a testing script? or a online pretrained model we can compare against?
> 
> Hi @KalraA
> I just saw your comments here. It seems that you could train their model. As I have some issues with the rendering module, would you please give me the details of your environment you used for training this code? I'm using ubuntu 18, python 2.7 and tensorflow 1.8 and I'm facing errors when I run the main code. The error I get when I run the rendering_example.py is as follows:
> The error I get when I run rendering_example.py:
> InternalError: Blas xGEMMBatched launch failed : a.shape=[16,4,3], b.shape=[16,53215,4], m=3, n=53215, k=4, batch_size=16
> [[Node: MatMul = BatchMatMul[T=DT_FLOAT, adj_x=true, adj_y=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](concat, concat_1)]]
> [[Node: Reshape_43/_147 = _Recvclient_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1301_Reshape_43", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"]]
> 
> Any advice is highly appreciated.
I run rendering_example.py also occur to the error:
InternalError: Blas xGEMMBatched launch failed : a.shape=[16,4,3], b.shape=[16,53215,4], m=3, n=53215, k=4, batch_size=16
[[Node: MatMul = BatchMatMul[T=DT_FLOAT, adj_x=true, adj_y=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](concat, concat_1)]]
[[Node: Reshape_43/_147 = _Recvclient_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1301_Reshape_43", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"]]
would you like the share the solution with me?Thanks very much？I am looking forward to your reply!

**Comment by qaz8788817** [comment]
> > Ok great, now it's training. So I guess the next question is how can I make sure that it reproduces the results in the paper? Is there a testing script? or a online pretrained model we can compare against?
> 
> Hi @KalraA I just saw your comments here. It seems that you could train their model. As I have some issues with the rendering module, would you please give me the details of your environment you used for training this code? I'm using ubuntu 18, python 2.7 and tensorflow 1.8 and I'm facing errors when I run the main code. The error I get when I run the rendering_example.py is as follows: The error I get when I run rendering_example.py: InternalError: Blas xGEMMBatched launch failed : a.shape=[16,4,3], b.shape=[16,53215,4], m=3, n=53215, k=4, batch_size=16 [[Node: MatMul = BatchMatMul[T=DT_FLOAT, adj_x=true, adj_y=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](concat, concat_1)]] [[Node: Reshape_43/_147 = _Recvclient_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1301_Reshape_43", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"]]
> 
> Any advice is highly appreciated.

Hi, I've met the same problem. Can you share how you solve it? Thanks.
